completion of week 4 assessment
learn-academy-2022-alpha/week-4-assessment-omarbowen01 pull request #1
Opened 2022-03-15 20:07 UTC by omarbowen01

2022-03-17 00:45 UTC, elysemontano requested changes
Requesting some changes: Please make sure to add your functions to problems 2 and 3 in code challenges.  Also, do not merge until I approve this pull request.  You should be able to push the changes to the same branch and I will see the updated changes.

2022-03-17 00:45 UTC, elysemontano commented on code-challenges.test.js
> +})
This setup is a little trickier than our usual Jest test.  There may be a few syntax things on your expect statement and make sure to be checking the expected _output_.  It looks like you are currently checking the initial input in your expect.arrayContaining method.

2022-03-17 00:45 UTC, elysemontano commented on code-challenges.test.js
> +}
Logic looks great and excellent work on your pseudocode!  You may have one small syntax error that might make your test fail.  Just make sure your variable name casing for randomnum matches when you reference it.

2022-03-17 00:45 UTC, elysemontano commented on code-challenges.test.js
> +
I don't see a function written out.  Your pseudocode looks like you should be able to get there.

2022-03-17 00:45 UTC, elysemontano commented on code-challenges.test.js
> +//return the specific array
Pseudocode looks great and will definitely get you to where you want to be!  Please write out the function to go with it and run your test.  Remember, we want to run the test and see that we are getting the right kind of fail.  Then we write the function and check we are passing.  Please make sure to paste the test results for both fail and pass from your terminal in pseudocode.

2022-03-17 00:45 UTC, elysemontano commented on interview-questions.md
> +  Researched answer: When you don't specifically put 'return' in the return statement the function will output the result of the last evaluated expression.
Great job in this section!

2022-03-17 00:45 UTC, elysemontano commented on ruby-challenges.rb
> +p even_or_odd num3
Awesome!!  Ruby also has a handy built-in method that will give a boolean if a number is even and if a number is odd.

2022-03-17 00:45 UTC, elysemontano commented on ruby-challenges.rb
> +p vowel_taker album3
Excellent!  Please make sure to leave your variables uncommented out.  Any part of the code needed to run the file should be left commented in.

2022-03-17 00:45 UTC, elysemontano commented on ruby-challenges.rb
> +def palindrome String
String should be in the casing convention of snake_case since this will be used as a param in the method.  PascalCasing is reserved for when we refer to a class.

2022-03-17 00:45 UTC, elysemontano commented on ruby-challenges.rb
> +p palindrome is_palindrome3
Your logic looks great, there are a few small syntax errors on this problem. On line 73, it looks like you are not comparing the values in your statement, I would recommend equality operator here.  There also may be an extra double quote just after #{word} on line 76.

2022-03-23 17:15 UTC, elysemontano approved these changes
Great work Omar!  Your pseudocode does a really good job describing your approach.  When writing out the functions in the code challenges, it is always good to check back with your pseudocode to make sure you have done all the steps.  Also, what does your terminal say when running the tests?  Always keep a close eye on the data type you are working with for both input and outputs.

2022-03-23 17:15 UTC, elysemontano commented on code-challenges.test.js
> +// })
Test is really close.  May want to check the syntax for arrayContaining and also make sure your expected output is accurate in your test.  Looks like you put the input there.

2022-03-23 17:15 UTC, elysemontano commented on code-challenges.test.js
> +// }
Logic looks great!  Make sure to have the same casing for your variables when accessing them in your function.  Looks like randomnum is different from line 48 to 49.  Also, please make sure to leave code uncommented in your PR.

2022-03-23 17:15 UTC, elysemontano commented on code-challenges.test.js
> +//   console.log(minAndMax(nums2))
I like your logic in using the Math.min and Math.max with the spread operator.  A function will only return one thing though, so you would need to combine the 2 numbers into an array and return that array.

2022-03-23 17:15 UTC, elysemontano commented on code-challenges.test.js
> +// })
Syntax and logic looks good in the test.  Just make sure that your data type in the array matches what you are expecting.

2022-03-23 17:15 UTC, elysemontano commented on code-challenges.test.js
> +// })
Looks like your test is asking for numbers as strings instead of numbers. Keep an eye on the data types you are working with both input and output.

2022-03-23 17:15 UTC, elysemontano commented on code-challenges.test.js
> +//   console.log(noDuplicates(uniqueArrays))
Definitely heading in the right direction.  You started a filter, but what do you want to filter out?  You mentioned checking index in your pseudocode which seems like that would be a good approach.

2022-03-29 00:56 UTC, omarbowen01 commented on code-challenges.test.js
> +
function is there

2022-03-29 01:02 UTC, omarbowen01 commented on code-challenges.test.js
> +//return the specific array
done

2022-03-31 21:08 UTC, merged